### ISSUE TITLE
Full composer support

### ISSUE THREAD

**Issue by mwjames** [rdfio/RDFIO#13]
After  `zahara/RDFIO` has been merged into master, it would be possible to add `semsol/arc2` as dependency to `mediawiki/rdfio`.

```
	"require": {
		"composer/installers": ">=1.0.1",
		"mediawiki/semantic-media-wiki": ">=2.3",
		"semsol/arc2": "v2.2.4"
	},
```

``mediawiki/rdfio` requires registration with https://packagist.org/ in order to allow for proper download.

This would allow to eliminate the manual step of `libs` creation in SMW-core (which should not be done at all) and it would ensure that ARC2 classes are autoloaded when registered through Composer without making it a hard dependency in 

```
$smwgARC2Path = $smwgIP . '/libs/arc/';
$smwgARC2MainFile = $smwgARC2Path . '/ARC2.php';
if ( ! file_exists( $smwgARC2MainFile )) {
	throw new MWException("ARC2 library is not installed in Semantic Mediawiki libs folder! Please refer to the installation instructions, to fix that: http://www.mediawiki.org/wiki/Extension:RDFIO#Installation");
} else {
	require_once( $smwgARC2MainFile );
}
```

**Comment by samuell** [comment]
Great, thanks for the heads up! Will have a look at this shortly.

**Comment by mwjames** [comment]
> Great, thanks for the heads up! Will have a look at this shortly.

That would be great because once you have that sorted it might make it possible to have this work with SMW 2.3. I can sent some smaller clean-up PR's once the installation works with Composer.

Once the Composer is working standard release tags should help to match RDFIO with SMW compatibility.

**Comment by mwjames** [comment]
Maybe tag the current master as 1.9.? release then it is possible to merge `develop` into master and 
have its `composer.json` to add

```
	"extra": {
		"branch-alias": {
			"dev-master": "2.0.x-dev"
		}
	},
```

which would if released distinguish it clearly from the 1.9. Users that want the old master can to so be selecting 1.9* from the https://github.com/samuell/RDFIO/releases.

**Comment by samuell** [comment]
@zahara now working on this, in #21

**Comment by samuell** [comment]
@mwjames So, that will require that we tag the main master branch with `2.0.x-dev` also, somehow?

**Comment by samuell** [comment]
@mwjames I have now tried to add @zahara and mine latest changes, according to your suggestions above, into the rdfio/RDFIO master branch. Feel very much free to check out and comment if something still needs fixing.

**Comment by mwjames** [comment]
> So, that will require that we tag the main master branch with 2.0.x-dev also, somehow, or, it is just an alias to master?

If you tag master with 2.0 then Composer (if registered with https://packagist.org/) will retrieve the tags from github and match the sha1.

For SMW, we add an alias to the `composer.json`, so that someone who wants to use the dev version is redirect to the correct tag.

Whenever we change a minor/major version, we adapt the alias as well.

```
	"extra": {
		"branch-alias": {
			"dev-master": "2.5.x-dev"
		}
	},
```

https://getcomposer.org/doc/articles/aliases.md

**Comment by samuell** [comment]
@mwjames Thanks for info! Is it sensible to the difference between "v0.0...." and "0.0...."? (then I need to update the composer.json slightly, as we went with the v0.0 scheme since before)

**Comment by mwjames** [comment]
> Feel very much free to check out and 

Testing the install isn't possible yet since `mediawiki/rdfio` has been registered with https://packagist.org/search/?q=mediawiki%2Frdfio&reason=package_not_found.

**Comment by samuell** [comment]
@mwjames Yep - working on that! :)

**Comment by samuell** [comment]
@mwjames Published as `rdfio/rdfio` on packagist now. It is installable and shows up as RDFIO under Special:Version, but none of the special pages are included, so something is screwed up with the file or class loading within RDFIO.

**Comment by mwjames** [comment]
>  but none of the special pages are included, so something is screwed up with the file or class loading within RDFIO.

[0] contains reference to `wg...` and I think we want $GLOBALS[....] here to make sure that those initialised in time.

[0] https://github.com/rdfio/RDFIO/blob/master/specials/SpecialRDFIOAdmin.php

**Comment by samuell** [comment]
@mwjames Ah, yes, thanks! Strange that I didn't see that, although I was fixing similar errors elsewhere before, and just had a look in these files. Will test and try again.

**Comment by samuell** [comment]
Ok, getting closer now: https://github.com/rdfio/RDFIO/releases/tag/v2.0.2

Remaining issues now are
- Didn't manage to access db connection info from LocalSettings.php (neither `global $wgDB...` nore `$GLOBALS['wgDB...` strategies worked here), so have to configure db connections manually again in `RDFIO.php`.
- Found a bug with WikiObjectModel. Optimally I would really like to drop the WOM dependency.

Have to go for now, checking back tomorrow or later tonight.

**Comment by mwjames** [comment]
> Didn't manage to access db connection info from LocalSettings.php 

You need to access information from `LocalSettings` then you have defer the access using something like:

```
$GLOBALS['wgExtensionFunctions'][] = function() {
	SemanticMediaWiki::onExtensionFunction();
};
```

https://www.mediawiki.org/wiki/Manual:$wgExtensionFunctions

> Found a bug with WikiObjectModel. Optimally I would really like to drop the WOM dependency.

I think that would be the best option.

**Comment by zahara** [comment]
I did write code to remove this dependency in an as yet unmerged branch, but I've learned a lot since then so am pretty sure it's terrible.  Schedule's pretty busy for the next couple of months with conferences etc., so can't guarantee I'll be able to look at it soon.

**Comment by samuell** [comment]
@zahara Ah, sorry, I might have missed that. I based my latest branch off of your SMW_2.3 branch, with some fixes of my own, though, but didn't do any extensive looking in the other branches. Might have another look.

Anyways, I do understand your time situation. It is typically the same for me :) ... only just now having the opportunity to work on it as part of main job for a few weeks, so trying to push it a bit :)

**Comment by samuell** [comment]
@mwjames Awesome, the extensionfunctions thingy helped!

Got it to work with:
```php
$GLOBALS['wgExtensionFunctions'][] = function() {
    global $wgDBtype, $wgDBserver, $wgDBname, $wgDBuser, $wgDBpassword, $wgDBprefix;
    global $smwgARC2StoreConfig, $smwgDefaultStore;
    $smwgARC2StoreConfig = array(
        'db_host' => $wgDBserver,
        'db_name' => $wgDBname,
        'db_user' => $wgDBuser,
        'db_pwd' =>  $wgDBpassword,
        'store_name' => $wgDBprefix . 'arc2store', // Determines table prefix
    );  
    $smwgDefaultStore = 'SMWARC2Store';
};
```
Did not google-find any info about `SemanticMediaWiki::onExtensionFunction();` though?

@zahara Will for sure have a look at any code you already have. Some pointers to which branch I should look at?

**Comment by samuell** [comment]
@zahara Ah, never mind, I see your changes to drop WOM are already in - my bad!

**Comment by samuell** [comment]
Everything related to composer seems to work now, after release [v2.0.4](https://github.com/rdfio/RDFIO/releases/tag/v2.0.4), so closing this. Please re-open if any remaining issues are found.

RDFIO is [available on packagist](http://packagist.org/packages/rdfio/rdfio) under `rdfio/rdfio` now, and the [README install instructions](https://github.com/rdfio/RDFIO#installation) are updated.
