### ISSUE TITLE
Remove remnant .svn files

### ISSUE THREAD

**Issue by samuell** [rdfio/RDFIO#17]
Turns out there are a couple of trailing .svn files checked in to git:

``` bash
[vagrant RDFIO]$ find | grep svn
./stores/.svn
./stores/.svn/prop-base
./stores/.svn/prop-base/SMW_ARC2Store.php.svn-base
./stores/.svn/entries
./stores/.svn/text-base
./stores/.svn/text-base/SMW_ARC2Store.php.svn-base
./bundle/.svn
./bundle/.svn/prop-base
./bundle/.svn/prop-base/ARC2_SPARQLSerializerPlugin.php.svn-base
./bundle/.svn/entries
./bundle/.svn/text-base
./bundle/.svn/text-base/ARC2_SPARQLSerializerPlugin.php.svn-base
```

**Comment by zahara** [comment]
Would this be a simple case of removing the SVN folder?  Or would we need to port them to Git somehow to keep the history?

**Comment by samuell** [comment]
@zahara I think the reason they are not already removed is that I thought one might try to delete them completely from history as well, just to clean things up. I have some notes of the commands needed, so could have a look.

**Comment by samuell** [comment]
Fixed as of 26ad48
