### ISSUE TITLE
Article::doEdit() dropped in MW 1.29 (deprecated in 1.21)

### ISSUE THREAD

**Issue by reedy** [rdfio/RDFIO#31]
https://gerrit.wikimedia.org/r/#/c/326326/ was made by a GCI student, if you want to import it to this repo

**Comment by feelfreelinux** [comment]
Should i make pull request?

**Comment by samuell** [comment]
@feelfreelinux Absolutely, feel free to send a pull request! Just please base it off of this repo's current version of SMWPageWriter, as there is probably quite some substantial changes made to this repo after the one in the MW repo, which is very outdated.

But if you send a PR, we can discuss any minor issues in the PR, after I have checked it.

**Comment by samuell** [comment]
Just a note for the record that `Article::doEdit()` was finally dropped in MW 1.29, as [stated in the release notes](https://www.mediawiki.org/wiki/Release_notes/1.29#Other_changes_in_1.29).

**Comment by samuell** [comment]
Thanks tons, @feelfreelinux , implemented now!
