### ISSUE TITLE
Showing Special pages

### ISSUE THREAD

**Issue by kghbln** [rdfio/RDFIO#49]
RDFIO shows its special pages also to people not permitted to use them, even to anonymous users. I believe a permission error should be shown instead like [SMW and other extensions do it too.](https://www.semantic-mediawiki.org/wiki/Special:SemanticMediaWiki)

I think this is a pretty urgent issue.

**Comment by kghbln** [comment]
By the way. Does RDFIO define specialized permissions or are the actions tied to a standard group like user or sysop?

**Comment by samuell** [comment]
@kghbln Ah, good point, about not even showing the special pages!

RDFIO does so far just use the standard edit permission.

Then, there's a question about what to do about the SPARQL endpoint ... could be usable to anon users, although a risk for bad usage. I guess could make sense for a specialized permission there ...

**Comment by samuell** [comment]
So, as per request, posting here too, what RDFIO currently does, when

```
wgGroupPermissions['*']['edit'] = false;
```

![rdf import - semantic-mediawiki org - chromium_322](https://user-images.githubusercontent.com/125003/29171455-f76e3f44-7ddc-11e7-9cda-f9b46b03d025.png)

![sparql endpoint - semantic-mediawiki org - chromium_321](https://user-images.githubusercontent.com/125003/29171460-fb38671c-7ddc-11e7-8c87-c240a27e756e.png)

**Comment by kghbln** [comment]
> So, as per request, posting here too, what RDFIO currently does, when

I guess it will be a nice enhancement to have something like rdfioadmin, rdfioimport and rdfioexport

**Comment by samuell** [comment]
> I guess it will be a nice enhancement to have something like rdfioadmin, rdfioimport and rdfioexport

Absolutely! Will have a go at it. Feel free to suggest if there are any more details about how to best config this.

**Comment by samuell** [comment]
Ok, so just for ref, this is the exact code for what each Special page checks before doing any edits, right now: https://github.com/rdfio/RDFIO/blob/master/classes/RDFIO_SpecialPage.php#L62-L84

**Comment by mwjames** [comment]
> something like rdfioadmin, rdfioimport and rdfioexport

I'll go with `rdfio-...` as rights name.

**Comment by samuell** [comment]
Sorry for the delay ... stuff happening at work. Trying to have a look now.

**Comment by samuell** [comment]
So, if I understand the [SMW code](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/16285d5/src/MediaWiki/Specials/SpecialAdmin.php#L31-L33) correctly, I would simply do something like:

```php
	public function __construct() {
		parent::__construct( 'RDFIOAdmin', 'rdfio-admin' );
	}
```
... for all restricted special pages, and then in the `execute()`:

```php
		if ( !$this->userCanExecute( $this->getUser() ) ) {
			// $this->mRestriction is private MW 1.23-
			throw new ExtendedPermissionsError( 'rdfio-admin', array( 'rdfio-admin-permission-missing' ) );
		}
```

... and this latter code will do all the required permissions checking?

/me having a try ...

**Comment by samuell** [comment]
In 453c2a26543ff21a3322a2ef0a5436c9a0359faf I implemented three new permissions:
* `rdfio-admin`
* `rdfio-import`
* `rdfio-export`
... as per @kghbln's recommendations.

These are also assigned to user groups like so:

* `rdfio-admin`: sysop, smwadministrator, rdfioadministrator
* `rdfio-import`: sysop, smwadministrator, rdfioadministrator, smwcurator, rdfiocurator
* `rdfio-export`: sysop, smwadministrator, rdfioadministrator, smwcurator, rdfiocurator

This is in addition to the already available checks, which always checks for `edit` and `createpage` permissions before importing (see [here](https://github.com/rdfio/RDFIO/blob/fd2551e/classes/RDFIO_SpecialPage.php#L67-L77)) and `delete` access for deleting pages (see [here](https://github.com/rdfio/RDFIO/blob/fd2551e/classes/RDFIO_SpecialPage.php#L90-L96)).

**Comment by samuell** [comment]
Or maybe @JeroenDeDauw can comment (On https://github.com/rdfio/RDFIO/issues/49#issuecomment-322474372 and 453c2a26543ff21a3322a2ef0a5436c9a0359faf) ? :)

**Comment by kghbln** [comment]
> (Edit: Hmm, should perhaps the edit and createpage settings be assigned to rdfioadmin and rdfiocurator automatically ...?)

Aren't these already assigned to users? Since an `rdfioadmin` and `rdfiocurator` will most probably also be a user ...

**Comment by samuell** [comment]
Quoting @kghbln 
> Aren't these already assigned to users? Since an rdfioadmin and rdfiocurator will most probably also be a user ...

Ah, good point!

**Comment by samuell** [comment]
Maybe the main question I've been unsure about is with the SPARQL endpoint: It allows both export and import of data.

Thus, right now I put the main restriction to be `rdfio-export` on it, and then relying on the already available checks (`edit` and 'createpage`) to check whether people are allowed to insert stuff too.

Not sure if optimal, but it doesn't seem to make sense to completely block the endpoint if you don't have insert rights, since the querying/export use case is the most common any way...

**Comment by kghbln** [comment]
> Maybe the main question I've been unsure about is with the SPARQL endpoint

Ah, I did not think of this. Why not syncing this with the rights for accessing the respective special pages so people who have "rdfio-import" permission can also ... Probably I did not understand correctly.

**Comment by samuell** [comment]
There are a few options:

1. require rdfio-export
2. require rdfio-import
3. require either rdfio-export & rdfio-import
4. require both rdfio-export & rdfio-import

Right now it is 1. So you mean 3?

I was pondering 4.

**Comment by samuell** [comment]
I also have to check what can be done via the built in `canExecute` function ... not sure how complicated combinations are possible ...

**Comment by samuell** [comment]
Hmm, turns out the SpecialPage `__construct()` function only takes a single permission as input.

**Comment by samuell** [comment]
Ok, decided on it now:

Made a special `rdfio-sparql` permission, for the SPARQL endpoint, covering querying, export and import in one go.

Therebye the rdfio-export is also no longer needed for now (there's no dedicated export page right now).

Implemented in f6011b5

**Comment by samuell** [comment]
This is now in master. To be rolled out in v3.0.0 shortly (thought to bump the version because of the new permissions settings stuff).

**Comment by kghbln** [comment]
Cool, cool, cool. :)
