### ISSUE TITLE
Installing RDFIO 

### ISSUE THREAD

**Issue by ThiviyanThanapalasingam** [rdfio/RDFIO#53]
I am trying to follow the official [RDFIO manual installation guide](https://www.mediawiki.org/wiki/Extension:RDFIO#Medium-Hard:_Install_semi-manually_using_composer) to add the RDFIO extension to my Semantic Media Wiki (SMW). Originally, I SMW using Bitnami Media Stack v 1.29.1.  I am encountering a number of issue with the installation procedure and therefore, am in need of help. 

The first issue that I have is that adding `$smwgShowFactbox = SMW_FACTBOX_NONEMPTY;` to the localSettings.php file causes a Database error when I visit http://localhost:8080/wiki/Main_Page (see attached image file for more info).
<img width="1119" alt="screen shot 2017-11-27 at 19 25 03" src="https://user-images.githubusercontent.com/20305526/33284963-bbd6a2ce-d3a8-11e7-9fa4-608feba999cd.png">

The second issue is that I am not sure what is meant by the wiki_folder in `cd <wiki_folder>`. Can someone please clarify this?

**Comment by samuell** [comment]
Hi @ThiviyanThanapalasingam 

Could you provide me with what versions of MediaWiki and Semantic MediaWiki you have? (You should be able to find them on http://localhost:8080/wiki/Special:Version ... if  http://localhost:8080/wiki is your main wiki URL).

Regarding the `<wiki_folder>`, that is just a placeholder for the main mediawiki folder. That is, the same folder that contains the file `LocalSettings.php`. Hope that helps!

**Comment by ThiviyanThanapalasingam** [comment]
Hi @samuell 

Here are the versions that I am using:
- MediaWiki 1.29.1
- Semantic MediaWiki 2.5.4
- PHP 7.0.22 
- MySQL 5.6.37

Thanks.

**Comment by samuell** [comment]
Hi again,

What are the steps you have taken so far to install RDFIO?

Specifically, it seems the database tables used by RDFIO might not have been properly set up yet.

On this page in your wiki:
http://localhost:8080/wiki/Special:RDFIOAdmin

... have you clicked the "Setup" button there, and got a message that the RDFIO tables ("ARC2 store") are installed?

Best
// Samuel

**Comment by ThiviyanThanapalasingam** [comment]
Hello again, 

I have done the following steps:

- Added ```$smwgShowFactbox= SMW_FACTBOX_NONEMPTY;``` to localSettings.php

After carrying out the change and returning to the Semantic MediaWiki Main page, I saw the following database error message.

![](https://user-images.githubusercontent.com/20305526/33284963-bbd6a2ce-d3a8-11e7-9fa4-608feba999cd.png)

Nevertheless, I still went ahead with the installation. 

-  I have changed directory to the folder containing the *LocalSettings.php* file (before I had the chat with you I installed the extension into the wrong directory) and run the command `composer require rdfio/rdfio --update-no-dev`. Then, I headed over to http://localhost:8080/wiki/Special:RDFIOAdmin, after logging in as Admin, and I saw the following error message. 
<img width="790" alt="screen shot 2017-11-28 at 12 02 58" src="https://user-images.githubusercontent.com/20305526/33318849-24ef5aa4-d434-11e7-8009-cf37475785d6.png">

- Unfortunately, I did not get to the part where I set up the database.

**Version of RDFIO I have installed is 3.0.2.**

**Comment by ThiviyanThanapalasingam** [comment]
Here is what I have in my composer.json file, just in case.

```
{
	"name": "mediawiki/core",
	"description": "Free software wiki application developed by the Wikimedia Foundation and others",
	"keywords": ["mediawiki", "wiki"],
	"homepage": "https://www.mediawiki.org/",
	"authors": [
		{
			"name": "MediaWiki Community",
			"homepage": "https://www.mediawiki.org/wiki/Special:Version/Credits"
		}
	],
	"license": "GPL-2.0+",
	"support": {
		"issues": "https://bugs.mediawiki.org/",
		"irc": "irc://irc.freenode.net/mediawiki",
		"wiki": "https://www.mediawiki.org/"
	},
	"require": {
		"composer/semver": "1.4.2",
		"cssjanus/cssjanus": "1.2.0",
		"ext-ctype": "*",
		"ext-iconv": "*",
		"ext-json": "*",
		"ext-mbstring": "*",
		"ext-xml": "*",
		"liuggio/statsd-php-client": "1.0.18",
		"mediawiki/at-ease": "1.1.0",
		"oojs/oojs-ui": "0.21.1",
		"oyejorge/less.php": "1.7.0.14",
		"php": ">=5.5.9",
		"psr/log": "1.0.2",
		"wikimedia/assert": "0.2.2",
		"wikimedia/base-convert": "1.0.1",
		"wikimedia/cdb": "1.4.1",
		"wikimedia/cldr-plural-rule-parser": "1.0.0",
		"wikimedia/composer-merge-plugin": "1.4.0",
		"wikimedia/html-formatter": "1.0.1",
		"wikimedia/ip-set": "1.1.0",
		"wikimedia/php-session-serializer": "1.0.4",
		"wikimedia/relpath": "1.0.3",
		"wikimedia/remex-html": "1.0.1",
		"wikimedia/running-stat": "1.1.0",
		"wikimedia/scoped-callback": "1.0.0",
		"wikimedia/utfnormal": "1.1.0",
		"wikimedia/timestamp": "1.0.0",
		"wikimedia/wait-condition-loop": "1.0.1",
		"wikimedia/wrappedstring": "2.2.0",
		"zordius/lightncandy": "0.23",
		"rdfio/rdfio": "^3.0"
	},
	"require-dev": {
		"composer/spdx-licenses": "1.1.4",
		"hamcrest/hamcrest-php": "^2.0",
		"jakub-onderka/php-parallel-lint": "0.9.2",
		"jetbrains/phpstorm-stubs": "dev-master#1b9906084d6635456fcf3f3a01f0d7d5b99a578a",
		"justinrainbow/json-schema": "~3.0",
		"mediawiki/mediawiki-codesniffer": "0.7.2",
		"monolog/monolog": "~1.22.1",
		"nikic/php-parser": "2.1.0",
		"nmred/kafka-php": "0.1.5",
		"phpunit/phpunit": "4.8.35",
		"psy/psysh": "0.8.5",
		"wikimedia/avro": "1.7.7",
		"wikimedia/testing-access-wrapper": "~1.0",
		"wmde/hamcrest-html-matchers": "^0.1.0"
	},
	"suggest": {
		"ext-apc": "Local data and opcode cache",
		"ext-curl": "Improved http communication abilities",
		"ext-fileinfo": "Improved mime magic detection",
		"ext-intl": "ICU integration",
		"ext-wikidiff2": "Diff accelerator",
		"monolog/monolog": "Flexible debug logging system",
		"nmred/kafka-php": "Send debug log events to kafka",
		"pear/mail": "Mail sending support",
		"pear/mail_mime": "Mail sending support",
		"pear/mail_mime-decode": "Mail sending support",
		"wikimedia/avro": "Binary serialization format used with kafka"
	},
	"autoload": {
		"psr-0": {
			"ComposerHookHandler": "includes/composer"
		},
		"files": [
			"includes/compat/Timestamp.php"
		]
	},
	"autoload-dev": {
		"files": [
			"vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php",
			"vendor/wmde/hamcrest-html-matchers/src/functions.php"
		]
	},
	"scripts": {
		"lint": "parallel-lint --exclude vendor",
		"phpcs": "phpcs -p -s",
		"fix": "phpcbf",
		"pre-install-cmd": "ComposerHookHandler::onPreInstall",
		"pre-update-cmd": "ComposerHookHandler::onPreUpdate",
		"test": [
			"composer lint",
			"composer phpcs"
		]
	},
	"config": {
		"optimize-autoloader": true,
		"prepend-autoloader": false
	},
	"extra": {
		"merge-plugin": {
			"include": [
				"composer.local.json"
			],
			"merge-dev": false
		}
	}
}

```

**Comment by samuell** [comment]
Hi, Ok, so you never had the chance to do the database setup on the RDFIOAdmin page?

Then, I think you will need to tell MediaWiki to output more details about the error, to know what the problem is.

Could you add, in LocalSettings.php:

```php
$wgShowExceptionDetails = true;
$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgShowDBErrorBacktrace = true;
error_reporting( -1 );
ini_set( 'display_errors', 1 );
```

(More info about debugging options [here](https://www.mediawiki.org/wiki/Manual:How_to_debug))

... and then tell what the output is, on the RDFIOAdmin page?

**Comment by ThiviyanThanapalasingam** [comment]
Hi Samuell, 

That is correct. I was not able to set up the database. 

**After adding the snippet of code to the LocalSettings.php and then going back to http://localhost:8080/wiki/Special:RDFIOAdmin, I saw the following message:** 

# Internal error
[dd6867fb48c5c9431f3545cd] /mediawiki/Special:RDFIOAdmin RuntimeException from line 228 of /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/MediaWiki/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT o_id AS id0,o0.smw_title AS v0,o0.smw_namespace AS v1,o0.smw_iw AS v2,o0.smw_sortkey AS v3,o0.smw_subobject AS v4 FROM `smw_fpt_pplb` INNER JOIN `smw_object_ids` AS o0 ON o_id=o0.smw_id WHERE s_id='2' 
Function: SMWSQLStore3Readers::fetchSemanticData
Error: 1146 Table 'bitnami_mediawiki.smw_fpt_pplb' doesn't exist (localhost:3306)

#0 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(933): Wikimedia\Rdbms\Database->reportQueryError('Table 'bitnami_...', 1146, 'SELECT o_id AS...', 'SMWSQLStore3Rea...', false)
#1 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/libs/rdbms/database/Database.php(1269): Wikimedia\Rdbms\Database->query('SELECT o_id AS...', 'SMWSQLStore3Rea...')
#2 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(225): Wikimedia\Rdbms\Database->select('`smw_fpt_pplb` ...', 'o_id AS id0,o0....', 's_id='2'', 'SMWSQLStore3Rea...', Array, Array)
#3 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(386): SMW\MediaWiki\Database->select('`smw_fpt_pplb` ...', 'o_id AS id0,o0....', 's_id='2'', 'SMWSQLStore3Rea...', Array)
#4 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(183): SMWSQLStore3Readers->fetchSemanticData(2, Object(SMW\DIWikiPage), Object(SMW\SQLStore\PropertyTableDefinition))
#5 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(232): SMWSQLStore3Readers->getSemanticDataFromTable(2, Object(SMW\DIWikiPage), Object(SMW\SQLStore\PropertyTableDefinition))
#6 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DirectEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty), NULL)
#7 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(213): SMW\SQLStore\EntityStore\DirectEntityLookup->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty), NULL)
#8 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/CachedPropertyValuesPrefetcher.php(100): SMWSQLStore3->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty), NULL)
#9 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertySpecificationLookup.php(424): SMW\CachedPropertyValuesPrefetcher->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty))
#10 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertySpecificationLookup.php(136): SMW\PropertySpecificationLookup->findPreferredPropertyLabel(Object(SMW\DIProperty), 'en')
#11 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertyLabelFinder.php(146): SMW\PropertySpecificationLookup->getPreferredPropertyLabelBy(Object(SMW\DIProperty), 'en')
#12 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertyRegistry.php(390): SMW\PropertyLabelFinder->findPreferredPropertyLabelByLanguageCode('_URI', 'en')
#13 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(231): SMW\PropertyRegistry->findPreferredPropertyLabelById('_URI', 'en')
#14 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(220): SMW\DIProperty->getPreferredLabel('en')
#15 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(181): SMWPropertyValue->parseUserValue('Equivalent URI')
#16 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/DataValueFactory.php(147): SMWDataValue->setUserValue('Equivalent URI', false)
#17 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/DataValueFactory.php(293): SMW\DataValueFactory->newDataValueByType('__pro', 'Equivalent URI', false, NULL, NULL)
#18 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(115): SMW\DataValueFactory->newPropertyValueByLabel('Equivalent URI')
#19 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequest/Deserializer.php(73): SMWPropertyValue::makeUserProperty('Equivalent URI')
#20 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequest.php(286): SMW\Query\PrintRequest\Deserializer::deserialize('Equivalent URI', false)
#21 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequestFactory.php(50): SMW\Query\PrintRequest::newFromText('Equivalent URI', false)
#22 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(277): SMW\Query\PrintRequestFactory->newPrintRequestFromText('Equivalent URI', false)
#23 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(332): SMWQueryProcessor::getComponentsFromFunctionParams(Array, false)
#24 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(189): SMWQueryProcessor::getQueryAndParamsFromFunctionParams(Array, 2, 1001, false, NULL)
#25 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(135): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(Array)
#26 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(298): SMW\ParserFunctions\AskParserFunction->parse(Array)
#27 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(3408): SMW\ParserFunctionFactory->SMW\{closure}(Object(Parser), '[[Category:RDFI...', '?Equivalent URI', '?RDFIO Import T...', 'format=table', 'mainlabel=Data ...', 'limit=10')
#28 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(3128): Parser->callParserFunction(Object(PPFrame_DOM), 'ask', Array)
#29 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Preprocessor_DOM.php(1199): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#30 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(2942): PPFrame_DOM->expand(Object(DOMElement), 0)
#31 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(1297): Parser->replaceVariables('\n{{#ask: [[Cate...')
#32 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(451): Parser->internalParse('\n{{#ask: [[Cate...')
#33 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/OutputPage.php(1768): Parser->parse('\n{{#ask: [[Cate...', Object(Title), Object(ParserOptions), true, true, NULL)
#34 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/OutputPage.php(1711): OutputPage->addWikiTextTitle('\n{{#ask: [[Cate...', Object(Title), true, false, true)
#35 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/Rdfio/specials/SpecialRDFIOAdmin.php(68): OutputPage->addWikiText('\n{{#ask: [[Cate...')
#36 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/specialpage/SpecialPage.php(522): RDFIOAdmin->execute(NULL)
#37 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#38 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Object(Title), Object(RequestContext))
#39 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(862): MediaWiki->performRequest()
#40 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(523): MediaWiki->main()
#41 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/index.php(43): MediaWiki->run()
#42 {main}

Backtrace:

#0 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(386): SMW\MediaWiki\Database->select(string, string, string, string, array)
#1 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(183): SMWSQLStore3Readers->fetchSemanticData(integer, SMW\DIWikiPage, SMW\SQLStore\PropertyTableDefinition)
#2 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(232): SMWSQLStore3Readers->getSemanticDataFromTable(integer, SMW\DIWikiPage, SMW\SQLStore\PropertyTableDefinition)
#3 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DirectEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#4 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(213): SMW\SQLStore\EntityStore\DirectEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#5 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/CachedPropertyValuesPrefetcher.php(100): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#6 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertySpecificationLookup.php(424): SMW\CachedPropertyValuesPrefetcher->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty)
#7 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertySpecificationLookup.php(136): SMW\PropertySpecificationLookup->findPreferredPropertyLabel(SMW\DIProperty, string)
#8 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertyLabelFinder.php(146): SMW\PropertySpecificationLookup->getPreferredPropertyLabelBy(SMW\DIProperty, string)
#9 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/PropertyRegistry.php(390): SMW\PropertyLabelFinder->findPreferredPropertyLabelByLanguageCode(string, string)
#10 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(231): SMW\PropertyRegistry->findPreferredPropertyLabelById(string, string)
#11 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(220): SMW\DIProperty->getPreferredLabel(string)
#12 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(181): SMWPropertyValue->parseUserValue(string)
#13 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/DataValueFactory.php(147): SMWDataValue->setUserValue(string, boolean)
#14 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/DataValueFactory.php(293): SMW\DataValueFactory->newDataValueByType(string, string, boolean, NULL, NULL)
#15 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(115): SMW\DataValueFactory->newPropertyValueByLabel(string)
#16 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequest/Deserializer.php(73): SMWPropertyValue::makeUserProperty(string)
#17 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequest.php(286): SMW\Query\PrintRequest\Deserializer::deserialize(string, boolean)
#18 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/Query/PrintRequestFactory.php(50): SMW\Query\PrintRequest::newFromText(string, boolean)
#19 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(277): SMW\Query\PrintRequestFactory->newPrintRequestFromText(string, boolean)
#20 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(332): SMWQueryProcessor::getComponentsFromFunctionParams(array, boolean)
#21 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(189): SMWQueryProcessor::getQueryAndParamsFromFunctionParams(array, integer, integer, boolean, NULL)
#22 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(135): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array)
#23 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(298): SMW\ParserFunctions\AskParserFunction->parse(array)
#24 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(3408): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string)
#25 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(3128): Parser->callParserFunction(PPFrame_DOM, string, array)
#26 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Preprocessor_DOM.php(1199): Parser->braceSubstitution(array, PPFrame_DOM)
#27 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#28 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(1297): Parser->replaceVariables(string)
#29 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/parser/Parser.php(451): Parser->internalParse(string)
#30 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/OutputPage.php(1768): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#31 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/OutputPage.php(1711): OutputPage->addWikiTextTitle(string, Title, boolean, boolean, boolean)
#32 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/extensions/Rdfio/specials/SpecialRDFIOAdmin.php(68): OutputPage->addWikiText(string)
#33 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/specialpage/SpecialPage.php(522): RDFIOAdmin->execute(NULL)
#34 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#35 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#36 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(862): MediaWiki->performRequest()
#37 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/includes/MediaWiki.php(523): MediaWiki->main()
#38 /Applications/mediawiki-1.29.1-0/apps/mediawiki/htdocs/index.php(43): MediaWiki->run()
#39 {main}

**Comment by samuell** [comment]
@ThiviyanThanapalasingam Aha, now I see.

It seems that the main Semantic MediaWiki (SMW) tables are not installed (It complains that one SMW table is missing: `bitnami_mediawiki.smw_fpt_pplb`).

And actually, from your composer.json file, it seems that SMW is not at all installed. SMW is a dependency for RDFIO, so you would need to install it first, following for example [these steps, to install it via composer](https://www.semantic-mediawiki.org/wiki/Help:Using_Composer). (General notes [here](https://www.semantic-mediawiki.org/wiki/Help:Installation)).

**Comment by ThiviyanThanapalasingam** [comment]
@samuell I just noticed that the post that I wrote to [RDFIO Wiki Discussion Board](https://www.mediawiki.org/wiki/Extension_talk:RDFIO) is not visible. Any reason why?

**Comment by samuell** [comment]
@ThiviyanThanapalasingam Great to hear that you managed to solve the issue!

Reg. the wiki, oh, I would recommend using this issue queue to start new discussions. The talk page on mediawiki.org is quite complex to handle, and it is very easy to miss some messages there.

Best
// Samuel
