### ISSUE TITLE
Bug 67798 - [RDFIO] -- notice and fatal error undefined variable and on non-object 

### ISSUE THREAD

**Issue by BMWPower** [rdfio/RDFIO#6]
What is going on? I import rdf/owl with function "PASTE"

Notice: Undefined variable: wikiPages in D:\xampp\htdocs\mediawiki\extensions\RDFIO\classes\RDFIO_RDFImporter.php on line 34

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\libs\arc\store\ARC2_Store.php on line 51

Fatal error: Call to a member function exists() on a non-object in D:\xampp\htdocs\mediawiki\extensions\RDFIO\classes\RDFIO_SMWPageWriter.php on line 24

**Comment by samuell** [comment]
Hi @BMWPower, thanks for reporting! A lot has changed since this was reported, so this error should hopefully not be occuring anymore, and I'm closing this. Please re-open if you run into similar issues with the latest version! (Note that you can now install the latest version [via composer, or using the vagrantbox](https://github.com/rdfio/RDFIO#installation)!)
