### ISSUE TITLE
Installing RDFIO Error SpecialRDFIOAdmin.php

### ISSUE THREAD

**Issue by andrecastro0o** [rdfio/RDFIO#65]
Hi,
I am trying to install RDFIO for the first time and am getting an error that I am not able to solve.
In the page `Special:RDFIOAdmin` I get the following error message:
```
[45d8462d54489c7d9d35e1af] /beerwiki/index.php/Special:RDFIOAdmin Error from line 67 of /var/www/html/beerwiki/extensions/Rdfio/specials/SpecialRDFIOAdmin.php: Call to undefined method OutputPage::addWikiText()

Backtrace:

#0 /var/www/html/beerwiki/includes/specialpage/SpecialPage.php(575): RDFIOAdmin->execute(NULL)
#1 /var/www/html/beerwiki/includes/specialpage/SpecialPageFactory.php(611): SpecialPage->run(NULL)
#2 /var/www/html/beerwiki/includes/MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#3 /var/www/html/beerwiki/includes/MediaWiki.php(900): MediaWiki->performRequest()
#4 /var/www/html/beerwiki/includes/MediaWiki.php(527): MediaWiki->main()
#5 /var/www/html/beerwiki/index.php(44): MediaWiki->run()
#6 {main}

```

I am running:
* MediaWiki | 1.34.1
* PHP | 7.3.14-1~deb10u1 (apache2handler)
* MariaDB | 10.3.22-MariaDB-0+deb10u1
* Semantic MediaWiki | 3.1.6
* RDFIO | v3.0.2

Help would be very appreciated :)

**Comment by samuell** [comment]
Hi @andrecastro0o , thanks for reporting!

This is probably related to the problems reported in #59. 

In the branch [59-make-work-with-mw-1.34](https://github.com/rdfio/RDFIO/tree/59-make-work-with-mw-1.34), there are fixes applied for most of the errors. Unfortunatly I haven't had the time to look into the final peculiarities. There is still something resulting in the round-trip system test failing, so I can't merge this into master and make a release just yet.

**Comment by samuell** [comment]
MediaWiki and especially SMW development is happening at a rather high pace, so it is at times a bit challenging to keep up with API changes on the limited time I have.

**Comment by andrecastro0o** [comment]
@samuell Thanks I will try to use the branch.
I understand. no need to apologize. 
I am quite curious about RDFIO as it seems a important piece to place smw instances within the larger context of semantic linked data.
:+1:  for the extension!!

**Comment by samuell** [comment]
@andrecastro0o Thank you! :slightly_smiling_face:

**Comment by andrecastro0o** [comment]
Nice.
Cloning the branch 59-make-work-with-mw-1.34 and renaming it Rdfio did the trick!
Thank you
