### ISSUE TITLE
No Continuous Integration

### ISSUE THREAD

**Issue by JeroenDeDauw** [rdfio/RDFIO#8]
RDFIO has PHPUnit tests, which is fantastic. If those where run for every commit on a CI service such as TravisCI, then finding issues will be a lot easier. People will also be able to contribute without having RDFIO set up, or review such contributions. This also makes it easier to detect compatibility issues with PHP, MW or SMW.

**Comment by samuell** [comment]
This is now [set up at CircleCI](https://circleci.com/gh/rdfio/RDFIO). Many thanks for raising the issue @JeroenDeDauw !

Test coverage is currently crap obviously, but now at least it is obvious :blush:

**Comment by samuell** [comment]
Well, the coverage is actually a bit better than this indicator ... seems to be something weird with `@cover` annotations or the test suite spec ...
